### ISSUE TITLE
電気の契約

### ISSUE THREAD

**Issue by cognitom** [opensource-town/okubo-67#10]

**Comment by kyinyo** [comment]
コープデリでんき　問い合わせ中
https://mirai.coopnet.or.jp/coopdelidenki/menu.html

**Comment by kyinyo** [comment]
#12 と同時検討

**Comment by kyinyo** [comment]
東京電力に開通依頼 3/21, 16:00ごろから利用開始予定

**Comment by kyinyo** [comment]
コープデリでんきでは手続き等の関係から3/21に開通は不可能とのこと。
コープデリでんきに変更するかは後日検討。
