### ISSUE TITLE
床下の状況の調査

### ISSUE THREAD

**Issue by cognitom** [opensource-town/okubo-67#18]

**Comment by cognitom** [comment]
和室左については問題ないことを確認。

**Comment by AlfaFoxt** [comment]
![UNADJUSTEDNONRAW_thumb_77a2](https://user-images.githubusercontent.com/2007604/55332159-cc0edb80-54cf-11e9-9b62-1f098bcc1d6f.jpg)
![UNADJUSTEDNONRAW_thumb_7767](https://user-images.githubusercontent.com/2007604/55332209-e648b980-54cf-11e9-8f8d-3d0521fefb05.jpg)
![UNADJUSTEDNONRAW_thumb_77a0](https://user-images.githubusercontent.com/2007604/55332246-f82a5c80-54cf-11e9-980f-2d763d15a6c8.jpg)
![UNADJUSTEDNONRAW_thumb_7791](https://user-images.githubusercontent.com/2007604/55332254-fa8cb680-54cf-11e9-9b32-288503f9f256.jpg)
![UNADJUSTEDNONRAW_thumb_775d](https://user-images.githubusercontent.com/2007604/55332322-18f2b200-54d0-11e9-9846-431e01139ac0.jpg)
![UNADJUSTEDNONRAW_thumb_7784](https://user-images.githubusercontent.com/2007604/55332330-1c863900-54d0-11e9-9985-0283d701dd75.jpg)
![UNADJUSTEDNONRAW_thumb_7770](https://user-images.githubusercontent.com/2007604/55332345-260fa100-54d0-11e9-9e29-80abea7da56b.jpg)
![UNADJUSTEDNONRAW_thumb_778c](https://user-images.githubusercontent.com/2007604/55332350-29a32800-54d0-11e9-96f3-eacd95f4b715.jpg)
![UNADJUSTEDNONRAW_thumb_7778](https://user-images.githubusercontent.com/2007604/55332365-2f990900-54d0-11e9-83bd-aaaaa68b4fc9.jpg)
